service: claude-lex-bedrock-bot

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-2
  environment:
    KNOWLEDGE_BASE_ID: ${env:KNOWLEDGE_BASE_ID, 'HKA5AHELTJ'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - bedrock:InvokeModel
            - bedrock:Retrieve
            - bedrock:RetrieveAndGenerate
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - lambda:InvokeFunction
            - lex:RecognizeText
            - lex:*
          Resource: "*"

functions:
  LexBedrockHandler:
    handler: handler.handler
    name: claude-lex-bedrock-bot-dev-LexBedrockHandler  # Static physical name
    events:
      - httpApi:
          path: /chat
          method: post

resources:
  Resources:
    MyLexBot:
      Type: AWS::Lex::Bot
      Properties:
        Name: MyBot
        DataPrivacy:
          ChildDirected: false
        IdleSessionTTLInSeconds: 300
        RoleArn: !GetAtt LexBotRole.Arn
        BotLocales:
          - LocaleId: en_US
            NluConfidenceThreshold: 0.40
            Intents:
              - Name: GreetingIntent
                SampleUtterances:
                  - Utterance: "Hi"
                  - Utterance: "Hello"
                  - Utterance: "Good morning"
                  - Utterance: "Hey"
                IntentClosingSetting:
                  ClosingResponse:
                    MessageGroupsList:
                      - Message:
                          PlainTextMessage:
                            Value: "Hello! How can I assist you today?"
              - Name: QueryIntent
                Slots:
                  - Name: query
                    SlotTypeName: AMAZON.AlphaNumeric  # Changed from AMAZON.SearchQuery
                    ValueElicitationSetting:
                      SlotConstraint: Required
                      PromptSpecification:
                        MessageGroupsList:
                          - Message:
                              PlainTextMessage:
                                Value: "What would you like to know?"
                        MaxRetries: 2
                SlotPriorities:  # Added to define slot priority
                  - SlotName: query
                    Priority: 1
                SampleUtterances:
                  - Utterance: "{query}"
                  - Utterance: "What is {query}"
                  - Utterance: "Tell me about {query}"
                  - Utterance: "Explain {query}"
                  - Utterance: "Can you help me with {query}"
                  - Utterance: "I want to know {query}"
                  - Utterance: "What do you know about {query}"
                IntentConfirmationSetting:
                  PromptSpecification:
                    MessageGroupsList:
                      - Message:
                          PlainTextMessage:
                            Value: "I’ll find an answer for your question: '{query}'. Is that okay?"
                    MaxRetries: 2
                FulfillmentCodeHook:
                  Enabled: true
              - Name: FallbackIntent
                ParentIntentSignature: AMAZON.FallbackIntent
                IntentClosingSetting:
                  ClosingResponse:
                    MessageGroupsList:
                      - Message:
                          PlainTextMessage:
                            Value: "I'm sorry, I didn't understand that. Could you please rephrase your question?"

    MyLexBotVersion:
      Type: AWS::Lex::BotVersion
      Properties:
        BotId: !Ref MyLexBot
        BotVersionLocaleSpecification:
          - LocaleId: en_US
            BotVersionLocaleDetails:
              SourceBotVersion: "DRAFT"
      DependsOn: MyLexBot

    MyLexBotAlias:
      Type: AWS::Lex::BotAlias
      Properties:
        BotAliasName: prod
        BotId: !Ref MyLexBot
        BotVersion: "1"
        BotAliasLocaleSettings:
          - LocaleId: en_US
            BotAliasLocaleSetting:
              Enabled: true
              CodeHookSpecification:
                LambdaCodeHook:
                  CodeHookInterfaceVersion: "1.0"
                  LambdaArn: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:claude-lex-bedrock-bot-dev-LexBedrockHandler"
      DependsOn: MyLexBotVersion
        
    LexBotRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lexv2.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LexBotAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - lambda:InvokeFunction
                    - bedrock:InvokeModel
                    - bedrock:Retrieve
                    - bedrock:RetrieveAndGenerate
                  Resource: "*"

    LexLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName: claude-lex-bedrock-bot-dev-LexBedrockHandler
        Principal: lexv2.amazonaws.com
        SourceArn: !Sub "arn:aws:lex:${AWS::Region}:${AWS::AccountId}:bot-alias/${MyLexBot}/${MyLexBotAlias}"

plugins:
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5

package:
  exclude:
    - node_modules/**
    - .git/**
    - .gitignore
    - test/**
    - "*.md"